# Generated by Django 5.2.7 on 2025-11-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatementSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_expense', models.DecimalField(decimal_places=2, max_digits=12)),
                ('avg_monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('avg_monthly_expense', models.DecimalField(decimal_places=2, max_digits=12)),
                ('risk_flag', models.CharField(max_length=32)),
            ],
        ),
    ]
